title: Notebooks
permalink: /:categories/:title/
intro: Hi, I'm <a href="https://twitter.com/jsvine">Jeremy Singer-Vine</a>, a journalist and computer programmer. This is my <i>notebooks</i> experiment. <a href="/introducting-reporter/">Click here for a more detailed explanation.</a>
footer: Built on <a href="/introducing-reporter/">Reporter</a>.
